### ISSUE TITLE
Event listener

### ISSUE THREAD

**Issue by cwfei** [federicoiosue/CheckListView#8]
Sorry for stupid questions, but how do I keep track the events such as check, un-check, arrange items, delete items and add new items, and also how can i display it as a TextView instead of editText and bind them into adapter for displaying in recyclerView, much thanks

**Comment by federicoiosue** [comment]
Actually events are not fired because I've developed the library to be auto-consistent and do everything on its own, but could be a nice improvement at low cost using something like EventBus.

For what concerns your second question I have to admit that I'm missing your point: you would like to show a **single** checklist item as reciclerview item or all the CheckListView component?

**Comment by cwfei** [comment]
Actually I'm developing a notes application where user can create either a simple note or a checklist, so the main screen will have a recycler view that display all those notes, I've no problem display them using normal text view, just wondering how to display checklist view, the numbers of checklist view is depending on the user, it can be many. BTW thanks for your reply and I appreciate your help.

**Comment by federicoiosue** [comment]
https://github.com/federicoiosue/Omni-Notes/blob/master/omniNotes/src/main/java/it/feio/android/omninotes/utils/TextHelper.java

Look around line 70.

That requires HTML parsing (computationally not convenient in a list) to show Unicode as symbols. 
If you find a better approach is very welcome!

**Comment by cwfei** [comment]
Thank you, I've been stuck for a long time, thanks for you help.
